### ISSUE TITLE
Light and Dark screenshots are the same

### ISSUE THREAD

**Issue by bramus** [tomayac/dark-mode-screenshot#1]
In commit 602b3d902b0499a50804533553a1a255bb3f154d the screenshots got renewed. They are, however, both the same screenshots.

**Comment by tomayac** [comment]
Yeah, I was in a hurry and deployed on a Friday before heading out for dinner. Don’t do that, lol. https://github.com/tomayac/dark-mode-screenshot/commit/03b981194963145c8f98535bb2abead582ab432f fixes this. Thanks for reporting!
