### ISSUE TITLE
Script seems to not be working in Kubuntu 18.04

### ISSUE THREAD

**Issue by Ghoelian** [tomayac/dark-mode-screenshot#2]
I'm using Kubuntu 18.04, so with KDE Plasma, and I have my theme set to Breeze Dark. The test pages I've tried in Firefox all detect I have a dark theme (even though that doesn't change when I switch both Firefox and KDE to a light theme), but this script gives me the following message:

Dark Mode needs to be on for this script to work. Please turn it on first.
👉 https://goo.gle/activate-dark-mode

![image](https://user-images.githubusercontent.com/33285224/65171500-4fef5c80-da4b-11e9-90d8-5b87401045b2.png)
![image](https://user-images.githubusercontent.com/33285224/65171556-6bf2fe00-da4b-11e9-87f7-1ef63dd6984a.png)

**Comment by tomayac** [comment]
I believe you're hitting a bug with dark theme detection in Chromium that we thought was fixed, but that was reopened recently. Could you please star [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=998903#c8) and once it's closed re-ping this issue (that I'm now closing in favor of the Chromium bug).
